on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install 
      - name: "Run Test"
        run: npm test