on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install 
      - name: "Run Test"
        run: npm test
      - name: "Pack files"
        run: npm run prepublish
      - uses: mikeal/merge-release@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}