on:
  push:
    branches:
      - main
    paths:
      - src/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
      - name: "Pack files"
        run: npm run prepublish
      - uses: mikeal/merge-release@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}